#!/usr/bin/env bash
cd "/d/Src/Needs of the Many/PluralBridge"
out="database/targeting/prop_candidate/pop_candidate_one_script_001_local_repeatbuild_001_006.sql"
printf "%s\n" "-- One Script 001 start" > "$out"
printf "%s\n" "-- Local validated 1-6 repeat-build from green checkpoint." >> "$out"
printf "%s\n" "-- Run in SSMS with master selected/highlighted." >> "$out"
printf "%s\n" "" >> "$out"
printf "%s\n" "-- Include: create repeatbuild database from validated baseline" >> "$out"
cat database/targeting/prop_candidate/pop_candidate_step_002_create_repeatbuild_database.sql >> "$out"
printf "%s\n" "" >> "$out"
printf "%s\n" "-- Include: literal APPARYLLIS seed" >> "$out"
cat database/targeting/prop_candidate/pop_candidate_step_007_seed_source_systems_literal.sql >> "$out"
printf "%s\n" "" >> "$out"
printf "%s\n" "-- Include: fixed first-pass 1-6 population" >> "$out"
cat database/targeting/prop_candidate/pop_candidate_step_014_003_populate_from_prequel_001_006_candidate_firstpass_fixed.sql >> "$out"
printf "%s\n" "" >> "$out"
printf "%s\n" "-- Include: 1-6 validation" >> "$out"
cat database/targeting/prop_candidate/pop_candidate_step_006_validate_001_006_slice.sql >> "$out"
printf "%s\n" "" >> "$out"
printf "%s\n" "-- One Script 001 end" >> "$out"
echo "VERIFY START"
ls -l "$out"
grep -n "One Script 001" "$out"
grep -n "DBCC CLONEDATABASE" "$out"
grep -n "literal APPARYLLIS seed" "$out"
grep -n "fixed first-pass 1-6 population" "$out"
grep -n "1-6 validation" "$out"
grep -n "prop_candidate_fail" "$out"
echo "FAIL_ARCHIVE_GREP_EXIT=$?"
echo "VERIFY END"
